##!/bin/bash

echo "Test exec.sh"
REPO_ECR_NAME="blender-repo-ecr"
BLENDER_VERSIONS="GPU-3.6.0,CPU-3.6.0,GPU-4.0.0"
AWS_ACCOUNT_ID="xxxxxxxxxxxx"
AWS_DEFAULT_REGION="us-east-1"

echo "REPO_ECR_NAME: $REPO_ECR_NAME"
echo "BLENDER_VERSIONS: $BLENDER_VERSIONS"
echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

bash build2.sh $REPO_ECR_NAME $BLENDER_VERSIONS $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION